"""Generate a one-off in-game script that pre-fills `seed.combos_tried`.

The save's state file already holds the planet's full seed recipe table
(`state.planet.plants.recipeMap`: {species: [3 life forms]}). This tool reads
it (read-only) and writes `scripts/_unmatched/seed_fill_tried.py` (gitignored,
save-specific) with the winning triples embedded. Run that script once in a
Seed Maker's slot: it marks every other triple of `self.life_forms()` as tried
(True), so the Stage A sweep in lib/seed_maker.py only ever combines real
recipes. Existing entries (tried or in-flight claims) are left untouched.
Do not use this script unless you're really tired of waiting for the Stage A 
sweep to finish. It is 100% cheating, but it is also 100% safe: it only 
marks non-recipe triples as tried, and it does not modify the save file itself. 


Usage:
    python devtools/seed_fill_tried.py [--save-dir PATH]
"""

import argparse
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from scripts_sync import discover_save, state_file_for  # noqa: E402

REPO = Path(__file__).resolve().parent.parent
OUT = REPO / "scripts" / "_unmatched" / "seed_fill_tried.py"

TEMPLATE = '''# One-off: mark every non-recipe life-form triple as tried in seed.combos_tried.
# Generated by devtools/seed_fill_tried.py from {save_name}. Run in a Seed Maker slot.

from archive import archive

TRIED_KEY = "seed.combos_tried"
CHUNK = 150          # keys per transaction; keeps each tick well under the 10,000-step limit
WINNERS = {winners!r}

forms = sorted(self.life_forms())
winners = set(WINNERS)
wrong = []
n = len(forms)
for i in range(n):
    for j in range(i + 1, n):
        for k in range(j + 1, n):
            key = forms[i] + "," + forms[j] + "," + forms[k]
            if key not in winners:
                wrong.append(key)
        sleep(0.05)  # yield the tick: at most ~28 keys per inner loop

added = []
batch = []


def updater(tried):
    if not isinstance(tried, dict):
        tried = {{}}
    for key in batch:
        if key not in tried:
            tried[key] = True
            added.append(key)
    return tried


for start in range(0, len(wrong), CHUNK):
    batch = wrong[start:start + CHUNK]
    archive.transaction(TRIED_KEY, {{}}, updater)
    sleep(0.1)
unknown = [w for w in WINNERS if not all(f in forms for f in w.split(","))]
print(f"seed_fill_tried: {{n}} forms, {{len(wrong)}} wrong triples, {{len(added)}} newly marked tried.")
if unknown:
    print(f"seed_fill_tried: WARNING recipe forms not in life_forms(): {{unknown}}")
'''


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--save-dir", type=Path, default=None)
    args = ap.parse_args()

    save_dir = args.save_dir or discover_save()
    state_path = state_file_for(save_dir) if save_dir else None
    if state_path is None:
        print("No save state file found.", file=sys.stderr)
        return 2

    with state_path.open(encoding="utf-8") as f:
        state = json.load(f).get("state", {})
    recipe_map = state.get("planet", {}).get("plants", {}).get("recipeMap") or {}
    if not recipe_map:
        print("No state.planet.plants.recipeMap in %s." % state_path, file=sys.stderr)
        return 2

    # Same key format as lib/seed_maker.py combo_key(): sorted names, comma-joined.
    winners = sorted(",".join(sorted(blend)) for blend in recipe_map.values())
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(TEMPLATE.format(save_name=state_path.name, winners=winners), encoding="utf-8")
    print("%d recipes from %s -> %s" % (len(winners), state_path.name, OUT))
    return 0


if __name__ == "__main__":
    sys.exit(main())
