#!/usr/bin/env python
"""Give Pyright a typed `self` in game scripts.

The game injects `self` (the machine a script runs on) as a global, so plain
Pyright reports `"self" is not defined` in every machine script. Each script
binds it to a typed name from the save's `user_stubs.py` instead:

    from typing import TYPE_CHECKING
    if TYPE_CHECKING:
        from user_stubs import o2gen as self

`TYPE_CHECKING` is false in game, so the import never runs and the injected
`self` stays in place. `user_stubs.py` is player-owned (the game creates it
once and never overwrites it) and both the in-game editor and the external
editor read it, so `self` resolves in both, and in Pyright through the copy
in `.pyright-resolved/stubs/`.

`scripts_sync.py` keeps a generated block between BLOCK_BEGIN and BLOCK_END
at the end of the save's `user_stubs.py`; text outside the block is kept. The
block is built from two game-shipped sources:
  - the game's language server (`external-ide/server/server.cjs`), whose
    machine definitions pair `nameKey:"machines.<type_id>.name"` with
    `scriptPrefix:"<prefix>"`;
  - the save's `__builtins__.pyi`, whose class for a type_id is its PascalCase
    (`oxygen_generator` -> `OxygenGenerator`), or failing that the class whose
    docstring starts with the machine's display name.
A prefix shared by several machine types (`drone`) becomes a union. Scripts
that run on no `scriptPrefix` machine come from SELF_TYPE_OVERRIDES.

    python devtools/self_typing.py apply [--dry-run]   # add the import to scripts that lack it
"""
import ast
import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
SCRIPT_ROOTS = (
    REPO / "scripts",
    REPO / "early_game_runner" / "templates",
    REPO / "early_game_runner" / "contracts",
    REPO / "early_game_runner" / "onboarding",
)
SKIP_PARTS = {"lib", "_unmatched", "__pycache__"}
CONTRACT_DIRS = {"contract", "contracts"}

STUB_MODULE = "user_stubs"
BLOCK_BEGIN = "# --- BEGIN typed self: generated by devtools/scripts_sync.py, edits inside this block are overwritten ---"
BLOCK_END = "# --- END typed self ---"
# Names for scripts that run on no scriptPrefix machine: name ->
# stub type expression. A contract script imports its contract id (its stem),
# generated from the stubs' per-contract classes; `contract` is the fallback
# for a contract the stubs don't describe.
SELF_TYPE_OVERRIDES = {
    "contract": "ContractScript",
    "oxygen_sensor": "OxygenSensor",
    "pressure_sensor": "PressureSensor",
    # Not a `self`: panel scripts get the injected global `panel` and import
    # it under its own name (`from user_stubs import panel`).
    "panel": "Panel",
}
# Component classes re-exported for scripts that bind a by-name lookup
# (`get_component("battery_1")`, typed plain Component) to its real type.
# Exported only when the save's __builtins__.pyi defines them.
COMPONENT_EXPORTS = (
    "BatteryComponent",
    "ChargingStation",
    "DroneLarge",
    "DroneMedium",
    "DroneServiceStation",
    "DroneSmall",
    "DroneStation",
    "DroneStationLarge",
    "DroneStationMedium",
    "Fabricator",
    "GasTank",
    "LargeWarehouse",
    "LiquidTank",
    "MiningDrill",
    "MiningDrillHeavy",
    "MiningDrillIndustrial",
    "OilPump",
    "OutpostComponent",
    "Smelter",
    "SteamTurbine",
    "SupplyDock",
    "Warehouse",
    "WaterPump",
    "WeatherStation",
)
# Script stems whose typed-self name differs from their slot-stripped stem.
STEM_ALIASES = {
    "pioneer_scout": "pioneer",
    "steam_turbine": "turbine",
}

MACHINE_DEF = re.compile(r'scriptPrefix:"([a-z0-9_]+)"')
NAME_KEY = re.compile(r'nameKey:"machines\.([a-z0-9_]+)\.name"')
DISPLAY_NAME = re.compile(r'"machines\.([a-z0-9_]+)\.name":"([^"]+)"')
STUB_CLASS = re.compile(r'^class (\w+)\([^)]*\):\n\s+"""([^:"\n]+):', re.M)
CONTRACT_CLASS = re.compile(r'^class (\w+)\(Contract\):\n\s+"""self\.contract \((\w+)\)"""', re.M)
NAME_KEY_LOOKBACK = 3000            # chars before scriptPrefix that hold the same definition's nameKey
TRAILING_INDEX = re.compile(r"_\d+$")


def server_path(save_dir: Path) -> Path:
    """The game's language server, installed beside the save folders."""
    return save_dir.parent / "external-ide" / "server" / "server.cjs"


def _pascal(type_id: str) -> str:
    return "".join(word.title() for word in type_id.split("_"))


def prefix_type_ids(server_text: str) -> dict:
    """{scriptPrefix: [type_id, ...]} from the language server's machine definitions."""
    result: dict = {}
    for m in MACHINE_DEF.finditer(server_text):
        keys = list(NAME_KEY.finditer(server_text, max(0, m.start() - NAME_KEY_LOOKBACK), m.start()))
        if not keys:
            continue
        type_ids = result.setdefault(m.group(1), [])
        if keys[-1].group(1) not in type_ids:
            type_ids.append(keys[-1].group(1))
    return result


def class_for(type_id: str, classes: dict, by_display: dict, display_names: dict):
    """Stub class name for a type_id, or None."""
    pascal = _pascal(type_id)
    if pascal in classes:
        return pascal
    return by_display.get(display_names.get(type_id, "").strip().lower())


def build_self_types(server_text: str, builtins_text: str):
    """(generated block, unresolved prefixes) for user_stubs.py."""
    classes = dict(STUB_CLASS.findall(builtins_text))
    by_display = {display.strip().lower(): name for name, display in classes.items()}
    display_names = dict(DISPLAY_NAME.findall(server_text))
    entries: dict = {}
    unresolved = []
    for prefix, type_ids in sorted(prefix_type_ids(server_text).items()):
        found = [class_for(type_id, classes, by_display, display_names) for type_id in type_ids]
        resolved = [name for name in found if name]
        if len(resolved) < len(found):
            unresolved.append(prefix)
            continue
        entries[prefix] = " | ".join(resolved)
    entries.update(SELF_TYPE_OVERRIDES)
    imports = {part.strip() for expr in entries.values() for part in expr.split("|")}
    imports.update(name for name in COMPONENT_EXPORTS
                   if re.search(r"^class %s\(" % name, builtins_text, re.M))
    script_classes = []
    for contract_class, contract_id in CONTRACT_CLASS.findall(builtins_text):
        script_class = "_%sScript" % contract_class
        script_classes += ["", "", "class %s(ContractScript):" % script_class, "    contract: %s" % contract_class]
        entries[contract_id] = script_class
        imports.add(contract_class)
    lines = [BLOCK_BEGIN, "from __builtins__ import %s" % ", ".join(sorted(imports))]
    lines += script_classes + ["", ""]
    # `= ...`: the game's language server exports only names a module binds;
    # a bare annotation binds nothing. The annotation stays the declared type.
    lines += ["%s: %s = ..." % (name, expr) for name, expr in sorted(entries.items())]
    lines.append(BLOCK_END)
    return "\n".join(lines) + "\n", unresolved


def merge_block(existing: str, block: str) -> str:
    """existing user_stubs.py text with its generated block replaced by block,
    or block appended when it has none. Text outside the block is kept."""
    start = existing.find(BLOCK_BEGIN)
    end = existing.find(BLOCK_END, start) if start >= 0 else -1
    if end >= 0:
        line_end = existing.find("\n", end)
        return existing[:start] + block + ("" if line_end < 0 else existing[line_end + 1:])
    if not existing or existing.endswith("\n\n"):
        separator = ""
    else:
        separator = "\n" if existing.endswith("\n") else "\n\n"
    return existing + separator + block


# ----------------------------------------------------------------- scripts
def self_type_name(path: Path) -> str:
    """The user_stubs name a script imports as `self`."""
    if path.parent.name in CONTRACT_DIRS:
        return path.stem
    stem = TRAILING_INDEX.sub("", path.stem)
    return STEM_ALIASES.get(stem, stem)


def script_files():
    for root in SCRIPT_ROOTS:
        for path in sorted(root.rglob("*.py")):
            if not SKIP_PARTS.intersection(path.relative_to(root).parts):
                yield path


def _is_type_checking(test) -> bool:
    return (isinstance(test, ast.Name) and test.id == "TYPE_CHECKING") or \
        (isinstance(test, ast.Attribute) and test.attr == "TYPE_CHECKING")


def uses_global_self(tree: ast.Module) -> bool:
    """True if `self` is read anywhere a function parameter doesn't bind it."""
    bound_in = set()
    for node in ast.walk(tree):
        if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef, ast.Lambda)):
            if any(arg.arg == "self" for arg in node.args.args + node.args.posonlyargs + node.args.kwonlyargs):
                bound_in.update(n for n in ast.walk(node) if n is not node)
    return any(isinstance(n, ast.Name) and n.id == "self" and n not in bound_in for n in ast.walk(tree))


def declared_self_type(tree: ast.Module):
    """The user_stubs name a script binds to `self`, or None."""
    for node in ast.walk(tree):
        if isinstance(node, ast.If) and _is_type_checking(node.test):
            for child in node.body:
                if isinstance(child, ast.ImportFrom) and child.module == STUB_MODULE:
                    for alias in child.names:
                        if alias.asname == "self":
                            return alias.name
    return None


def _insert_at(tree: ast.Module, lines: list) -> int:
    """Line index after the header: module docstring, `from __future__`
    imports and the comment lines that follow them."""
    index = 0
    for position, node in enumerate(tree.body):
        is_doc = position == 0 and isinstance(node, ast.Expr) and isinstance(node.value, ast.Constant) \
            and isinstance(node.value.value, str)
        is_future = isinstance(node, ast.ImportFrom) and node.module == "__future__"
        if not (is_doc or is_future):
            break
        index = node.end_lineno or node.lineno
    while index < len(lines) and lines[index].lstrip().startswith("#"):
        index += 1
    return index


def add_declaration(text: str, name: str) -> str:
    """text with the TYPE_CHECKING self import added after its header, in
    the text's own line endings."""
    eol = "\r\n" if "\r\n" in text else "\n"
    lines = text.splitlines(keepends=True)
    tree = ast.parse(text)
    has_flag = any(
        isinstance(node, ast.ImportFrom) and node.module == "typing"
        and any(alias.name == "TYPE_CHECKING" for alias in node.names)
        for node in tree.body
    )
    block = [] if has_flag else ["from typing import TYPE_CHECKING" + eol]
    block += ["if TYPE_CHECKING:" + eol, "    from %s import %s as self%s" % (STUB_MODULE, name, eol)]
    at = _insert_at(tree, lines)
    if has_flag:
        flag_line = max(node.end_lineno or node.lineno for node in tree.body
                        if isinstance(node, ast.ImportFrom) and node.module == "typing")
        at = max(at, flag_line)
    lead = [eol] if at and lines[at - 1].strip() else []
    tail = [eol] if at < len(lines) and lines[at].strip() else []
    return "".join(lines[:at] + lead + block + tail + lines[at:])


def apply(dry_run: bool = False) -> int:
    changed = 0
    for path in script_files():
        with open(path, encoding="utf-8", newline="") as handle:
            text = handle.read()
        tree = ast.parse(text)
        if not uses_global_self(tree) or declared_self_type(tree):
            continue
        name = self_type_name(path)
        print("%s %s -> %s" % ("would add" if dry_run else "added", path.relative_to(REPO), name))
        if not dry_run:
            path.write_text(add_declaration(text, name), encoding="utf-8", newline="")
        changed += 1
    print("%d script(s)" % changed)
    return changed


if __name__ == "__main__":
    if len(sys.argv) < 2 or sys.argv[1] != "apply":
        print(__doc__)
        sys.exit(2)
    apply(dry_run="--dry-run" in sys.argv[2:])
